<script>
$( function() {
    $(".elenco_utenti").click( function(e) {
        e.preventDefault();
        Dialog.init();
        Dialog.open("Funzione non ancora implementata.");
        }
    );
})

</script>
<h2>Elenco contratti esistenti</h2>
<p>[ Visualizza i contratti inseriti e ne permette la modifica ]</p>
<br /> 
<div id="view-content">
    <table>
        <thead>
            <th>ID</th>
            <th>Descrizione</th>
            <th></th>
            <th>Bisettimanale (Misto)</th>
            <th colspan="3"> Azioni </th>
        </thead>
    <?php foreach($this->list as $k => $v) { ?>
        <tr>
            <td><?php echo $v->contratto_id ?></td>
            <td><?php echo $v->descrizione ?></td>
            <td></td>
            <td>  <?php echo  $v->bisettimanale ?  "SI" :   "NO" ?> </td>

            <td>
                <a href="<?php echo $this->baseUrl('index.php')?>/contratti/edit/id/<?php echo $v->contratto_id?>">Modifica</a>
            </td>
            <td>
                <a href="<?php echo $this->baseUrl('index.php')?>/contratti/delete/id/<?php echo $v->contratto_id?>">Elimina</a>
            </td>
            <td>
                <a class= "elenco_utenti" href="<?php echo $this->baseUrl('index.php')?>/contratti/elenco-utenti/id/<?php echo $v->contratto_id?>">Elenco utenti</a>
            </td>
        </tr>
    <?php } ?>
    </table>
</div>
