<h3>Inserire nuova sede</h3>
 
<form action="" method="POST">
    <label>Città presenti</label>
    <select name="presenti">
        
        
        <?php foreach($this->sedi as $k=>$v) { ?>
        <option value="<?php echo $v->sede_id ?>"><?php echo ucfirst($v->citta) ?> </option>
        <?php } ?>
        
        
    </select>
    <br>
    <label>Inserire Città</label>
    <input type="text" name="citta" />
    <br>
    <input type="submit" name="submit" value="Salva" />
      
</form>