<?php
//$this->headScript()->appendFile($this->baseUrl().'/jquery.chromatable-1.3.0/jquery.chromatable.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/jquery.chromatable-1.3.0/css/style.css');
?>
<?php 
$status = array(
        "0" => "In lavorazione",
        "1" => "Accettato",
        "3" => "Rifiutato",
        "4" => "Annullato"
    );

$mesi = array(
        "0" => "Intero anno",
        "1" => "Gennaio", 
        "2" => "Febbraio",
        "3" => "Marzo",
        "4" => "Aprile",
        "5" => "Maggio",
        "6" => "Giugno",
        "7" => "Luglio",
        "8" => "Agosto",
        "9" => "Settembre",
        "10" => "Ottobre" ,
        "11" => "Novembre",
        "12" => "Dicembre"
          
 );
?>
 

<style type="text/css">
     .success{
        list-style-type: none;
        font-weight:bold;
        color:green;
        background-color:#8ae234;
        border-color:forestgreen;
        border-style: solid;
        border-width: 1px;
        width: 300px;
    }
    .rifiutato {
        color:red;
    }
    .accettato {
        color:green;
    }
    .odd {
        
    }
    .even {
        background-color:whitesmoke;
    }
     #panel {
        width: 500px;
    }
</style>

<script>
  $(function(){  
      
         var pathname = window.location.pathname;
         var l = window.location;
         var base_url = l.protocol + "//" + l.host + "/" + l.pathname.split('/')[1];
         var uid = "<?php echo $this->user_id ?>";
      
       $( "input[type=submit]" ).button();
       
        $("#storico").chromatable({
                  width: "100%", 
		  height: "auto" ,
                  scrolling: "yes"
	});	
        
        //dialog
        $("#richiesta").dialog({
            autoOpen: false,
            resizable: false,
            title: 'Inserisci motivo richiesta',
            modal: true,
            buttons: {
                "Invia" :  function(){
                    
                    user_id = $("#user_id").attr('value');
                    id = $("#richiesta_id").attr('value');
                    note = $("#note").val();
                    //console.log(user_id);
                    $.ajax({
                        type: 'POST',
                        url: base_url + '/public/index.php/richieste/annullarichiesta',
                        data: {
                            user_id: user_id,
                            richiesta_id: id,
                            note: note
                        },
                        dataType: 'json',
                        success: function(data) {
                            $("#note").val('');
                            $("#richiesta").dialog('close');
                            console.log(data);
                            alert('Richiesta di annullamento inoltrata');
                            
                            
                        },
                        error: function(xhr, ajaxOptions, thrownError) {
                            console.log('errore di salvataggio ');
                            alert('Errore invio richiesta di annullamento');
                            
                            
                            console.log(xhr.status + xhr.statusText + thrownError);
                            
                            
                        }
                    })
                },
                "Annulla" : function() {
                    $("#note").val('');
                    $(this).dialog('close');
                }
            }
        });
        
        
        /* richiesta annullamento ferie accettate */ 
        $(".canc-request").click(function(e){
            var id = $(this).attr('href');
            var msg = "Volete chiedere l'annullamento della richiesta numero " + id + " ?\n\n Cliccando su OK verrà inviata una email automatica all\'amministrazione.\n\n"
            var conferma = confirm(msg);
            if(conferma) {
                ask_cancellation_request_accepted(uid, id, function(data){
                    if(data.success == true) {
                        alert(data.message);
                    } else {
                        alert(data.message);
                    }
                });
            }
            e.preventDefault();
         
        });
        
        
  });
</script>
 
<form id="richiesta">
    <textarea id="note" rows="10" cols="30" ></textarea>
    <input type="hidden" name="richiesta_id" id="richiesta_id" /> 
    <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id ?>"/> 
</form> 

<h3>Storico richieste</h3>
<p>[ Permette di visualizzare la propria situazione, relativa alle richieste inserite. ]</p>
<p style="color:red;">Selezionare le opzioni dagli appositi menu a tendina e poi premere su <b>Cerca</b></p>
<form action="" method="post" >
    
    <table id="panel"> 
    <thead>
    <th>Stato della richiesta</th>
     <th>Mese</th>
      <th>Anno</th>
       <th></th>
    </thead>
    <tbody>
    <tr>
    <td>             
        <select name="status">
            <option value="<?php echo $this->status?>"><?php echo $this->status($this->status)?></option> 
            <?php foreach($status as $k => $v) { ?>
                    <?php if($this->status == $k) { continue; } ?>
                    <option value="<?php echo $k ?>"><?php echo $v ?></option>
            <?php } ?>
        </select>
    </td>
    <td>
        <select name="month">
            <option value="<?php echo $this->month ?>"><?php echo $mesi[$this->month] ?></option> 
            <?php for($i = 0; $i <= 12   ; $i++) { 
                if($i == $this->month) { continue; } ?>
              <option value="<?php echo $i?>"><?php echo $mesi[$i] ?></option>
            <?php } ?>
        </select> 
    </td>
    <td>
        <select name="year">
            <option value="<?php echo $this->year ?>"><?php echo $this->year ?></option> 
            <?php for($i = 2012; $i<=date('Y') + 1 ; $i++) { 
                if($i == $this->year) { continue; } ?>
              <option value="<?php echo $i?>"><?php echo $i ?></option>
            <?php } ?>
        </select>
    </td>
    <td>
        <input type="submit" name="submit"  value="Cerca" />
    </td>
    </tr>
    </tbody>
    </table> 
</form>

<p></p>






<?php if( isset($this->storico) &&   count($this->storico) > 0 ) { ?>

<table id="storico"  >
    <thead   align="left">
    <th>Richiesta N.</th>
    <th>Richiesta Del</th>
    <th>Periodo Dal</th>
    <th>Periodo Al</th>
    <th>Descrizione</th>
    <th>Totale giorni</th>
 
    <th>Sostituto</th>
 
    <th>Status</th>
    <th>Note</th>
    <th>Azioni</th>
    </thead>
    <tbody   align="left">
<?php
$now = new Zend_Date();
$counter = 0;
$msg = '';
        foreach ($this->storico as $row) {
           
            
            if($counter % 2) {
                $class = 'even';
            } else {
                $class = 'odd';
            }
            $counter++;
            if($row->status == 0) {
                
               //cancella 
               if((int)$row->created_by_user_id == (int)$this->user_id) { 
                $msg = "<a href='" . $this->baseUrl('index.php')."/richieste/cancella/richiesta_id/$row->richiesta_id'>Cancella</a>";
               } else {
                    $msg = "Assenza inserita dall'amministrazione";
               }
            } elseif($row->status == 1) {
                if((int)$row->created_by_user_id == (int)$this->user_id) {
                    $dateStart = new Zend_Date($row->dateStart);
                    if( (int)$dateStart->getTimestamp() > (int)$now->getTimestamp() )   {
                        $msg =  "<a class=\"canc-request\" href=\""  . $row->richiesta_id . "\">Richiedi Annullamento</a>";
                    } else {
                        $msg = "Nessuna azione disponibile";
                    }
                } else {
                    $msg = "Assenza inserita dall'amministrazione";
                }
            } else {
                $msg = '';
            }
            
            if($row->giorni == 0) {
                $giorni = Application_Service_Tools::getTotalDays($row->dateStart, $row->dateStop);
            } else {
                $giorni = $row->giorni;
            }
            
            if(isset($row->data_inizio)) {
                $inizio = $row->data_inizio;
            } else {
                $inizio = $row->dateStart;
            }
            
            if(isset($row->data_fine)) {
                $fine = $row->data_fine;
            } else {
                $fine = $row->dateStop;
            }
            
            
            echo '<tr class=\'' .$class.  '\'>
                <td> ' .$row->richiesta_id.'</td>
                <td> ' . $this->formatDate($row->date_insert,'d/m/Y') . ' </td>   
                <td> ' . $this->formatDate($inizio,'d/m/Y') . ' </td>
                <td> ' . $this->formatDate($fine,'d/m/Y') .  '</td>
                <td> ' . $this->descrizionetipo($row->tipologia_id).'</td>     
                <td> ' . $giorni .  '</td>';
                if($row->status == 1) {
                    echo ' <td> ' . $this->utente($row->sostituto_id) .  '</td>';
                } else {
                    echo '<td></td>';
                }
                echo '<td class=\'' . strtolower($this->status($row->status)) .  '\'> ' . $this->status($row->status) .  '</td>
                <td> ' . $row->note .  '</td>
                <td> ' . $msg .  '</td>   
                </tr>';           
        }
?>
    </tbody>
</table>

<?php }  else { ?>
     
<h4>Nessuna richiesta presente</h4>

<?php } ?>


<div align="center">
<?php 
//    if(isset($this->flashMessages())) {
 //       echo $this->flashMessages(); 
 //   }
?>
</div>
