<?php
 //$this->headScript()->appendFile($this->baseUrl().'/jquery.chromatable-1.3.0/jquery.chromatable.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/jquery.chromatable-1.3.0/css/style.css');
?>

<script>
  $(function(){  
        $("#listautenti").chromatable({
                width: "100%", 
		height: "auto" ,
                scrolling: "yes"
	});	
        
       $("SELECT").selectBox(); 
         $( "input[type=submit]" )
            .button()
            .click(function( event ) {}); 
        
        
        
        
  });
</script>

<h2>Budget</h2>

<p><a href="<?php echo $this->baseUrl('index.php')?>/budget/add/sostituzione_id/<?php echo $this->id ?>">Aggiungi nuovo importo</a></p>

<table width="90%">
    <thead align="left">
    <th>Budget ID#</th>
    <th width="100px">Sostituzione n. </th>
    <th>Sostituto</th>
    <th>Sede</th>
    <th>Dal</th>
    <th>Al</th>
    <th>Importo </th>
    <th>Modificato il</th>
    <th>Azioni</th>
    </thead>
    <tbody>
        
        <?php if(count($this->list) > 0) { ?>
            <?php foreach( $this->list as $row ) { ?>
            <tr>
                <td><?php echo $row->budget_id ?></td>
                <td><?php echo $row->sostituzione_id ?></td>
                
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                
                <td><?php echo $row->importo ?></td>
                <td><?php echo $this->formatDate($row->date) ?></td>
                <td>
                    <a href="<?php echo $this->baseUrl('index.php')?>/budget/update/budget_id/<?php echo $row->budget_id ?>">Modifica</a>
                 <a href="<?php echo $this->baseUrl('index.php')?>/budget/remove/sostituzione_id/<?php echo $row->sostituzione_id ?>/budget_id/<?php echo $row->budget_id ?>">Cancella</a>
                </td>
            </tr>
        
            
            <?php } ?>
        <?php } ?>
        
        
    </tbody>

</table>