<?php


$anno = $this->year;
$mese = $this->month;
$mesi = array(
        "1" => "Gennaio", 
        "2" => "Febbraio",
        "3" => "Marzo",
        "4" => "Aprile",
        "5" => "Maggio",
        "6" => "Giugno",
        "7" => "Luglio",
        "8" => "Agosto",
        "9" => "Settembre",
        "10" => "Ottobre" ,
        "11" => "Novembre",
        "12" => "Dicembre"
 );

echo "<table border=1 width=\"100%\">
        <thead>
        <th> 
        $mesi[$mese] $anno
        </th>";
        
       // if($mese < 10) {
       //        $mese = '0'.$mese; 
       // }
        
        for($i = 1; $i<=cal_days_in_month(CAL_GREGORIAN, $mese, $anno); $i++)  {
           echo "<th>" . $i . "</th>"; 
        }
        echo "</thead>";
        
foreach($this->dati as $nome => $v) {        
        echo "<tr>";
        echo "<td>" . $nome . "</td>";
        //procedura per il colore dei giorni del mese
        for($i = 1; $i<=cal_days_in_month(CAL_GREGORIAN, $mese, $anno); $i++)  {
           echo "<td>" . $v[$i] . "</td>"; 
        }
        
        echo "</tr>";
}
echo "</table>";
?>

