<h3>Modifica sostituto per <?php echo $this->operatore ?></h3>
 
<table>
    <tr><td><b>Sede</b></td><td><?php echo  $this->sede ?></td></tr>
    <tr><td><b>Dal</b></td><td><?php echo $this->formatDate($this->dal, 'd/m/Y') ?></td></tr>
    <tr><td><b>Al</b></td><td><?php echo  $this->formatDate($this->al, 'd/m/Y') ?></td></tr>
    <tr><td><b>Sostituto attuale</b></td><td><?php echo $this->sostituto  ?> </td></tr>
    
</table>

<br>


<form action="" method="POST">
    
    <table>
    <tr>
        <td>
            Sostituti liberi
        </td>
        <td>
            <select name="sostituto_id">
                <option value="">Seleziona sostituto</option>
                <?php foreach($this->liberi as $k => $v) { //print_r($v); ?>
                
                <option value="<?php echo $v->user_id ?>"><?php echo $v->cognome . ' ' . $v->nome ?></option>
                    
                <?php } ?>
                <option value="0">Nessun sostituto</option>
            </select>
        </td>
    </tr>
    
    <tr>
        <td>
            <input type="submit" name="submit" value="Aggiorna" />
            <input type="hidden" name="token" value="<?php echo $this->token ?>" /> 
        </td>
    </tr>
    </table>
        
    
    
</form>

