<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<html>
    <head>
 <?php 
        $top = null;

        $menu = null;

        if(Zend_Auth::getInstance()->hasIdentity()) {
            $identity =  Zend_Auth::getInstance()->getIdentity() ;
            $level = new Application_Model_LevelMapper();
            $role = $level->findByLevelId($identity->level_id)->descrizione;
            $this->identity_num = $identity->user_id;
            //$top = '<span class=\'identity\'>[' . $role . '] ' . $identity->nome . ' ' . $identity->cognome . '</span> <a class=\'logoutCls\' href="'.$this->baseUrl('index.php').'/auth/logout">Logout</a>'; 
            $top_identity = '<span class=\'identity\'>[' . $role . ']  </span> <a class=\'logoutCls\' href="'.$this->baseUrl('index.php').'/auth/logout">Logout</a>'; 
           
           
            $menubar = strtolower($role);
            $menu = $this->navigation()->menu()->renderMenu( $this->layout()->$menubar ); 
        } 
       
        
         $this->headLink()->appendStylesheet($this->baseUrl().'/development-bundle/themes/base/jquery.ui.all.css');
         $this->headScript()->appendFile($this->baseUrl().'/development-bundle/jquery-1.8.2.js');
         $this->headScript()->appendFile($this->baseUrl().'/jquery-ui-1.9.1/ui/jquery-ui.js');
         
         $this->headScript()->appendFile($this->baseUrl().'/jquery.formatCurrency-1.4.0/jquery.formatCurrency-1.4.0.js');
         $this->headScript()->appendFile($this->baseUrl().'/jquery.formatCurrency-1.4.0/i18n/jquery.formatCurrency.it-IT.js');
         
         $this->headLink()->appendStylesheet($this->baseUrl().'/development-bundle/demos/demos.css');
         $this->headScript()->appendFile($this->baseUrl().'/development-bundle/ui/ui.datepicker-it.js');
         
         $this->headScript()->appendFile($this->baseUrl().'/jquery.chromatable-1.3.0/jquery.chromatable.js');
         
         $this->headScript()->appendFile($this->baseUrl().'/jquery-selectBox-master/jquery.selectBox.min.js');
         $this->headLink()->appendStylesheet($this->baseUrl().'/jquery-selectBox-master/jquery.selectBox.css');
                  
         $this->headScript()->appendFile($this->baseUrl().'/js/functions.js');
         $this->headScript()->appendFile($this->baseUrl().'/js/Dialog.js');
        echo $this->headLink();
        echo $this->headScript() ;
        
        $title = 'Feriemanager - Gestionale assenze';
        $bgcolor ="#4287f5";
        if (Zend_Registry::isRegistered('sandbox')) {
            $value = Zend_Registry::get('sandbox');
             
        }
        if(true == $value) {
            $title = "[SANDBOX]" . '::' . $title;
            $bgcolor ="#292b2e";
        }  
        $this->headTitle()->prepend($title);
        echo $this->headTitle(); 
?>
        

<script type="text/javascript">
    
    showSpinner = function() {
        $('#spinner').show();
    }
    hideSpinner = function() {
        $('#spinner').hide(); 
    }
    $(document).ready(function () {	
        // parte lo spinner a ogni richiesta ajax
	$(this)
            .ajaxStart(showSpinner)
            .ajaxStop(hideSpinner)
            .ajaxError(hideSpinner)
            .ajaxComplete(hideSpinner) 
            .ajaxSuccess(hideSpinner)
        ;
        
	$('.navigation li').hover(
		function () {
                    // show menu
                    $('ul', this).stop().slideDown(100);
                }, 
		function () {
                    // hide menu
                    $('ul', this).stop().slideUp(100);			
		}
	);
	
    });
</script>
<style type="text/css">
    body {
        padding: 0px;
        margin: 0px;
        top:0px;
    }
    #barra_alta {
        color:white;
        background-color: <?php echo $bgcolor ?> ;
        width: 100%;
        margin: 0px;
        padding-bottom: 10px;
        border-bottom-style: solid; 
        border-bottom-width: 1px;
        border-bottom-color: #181e26;
    }
    #t0 {
        overflow: hidden;
         
        padding : 10px;
    }
    #t1 {
        float:left;
        width: 30%;
        padding:0px;
        margin:0px;
    }
    #t1 h2 {        
        padding:0px;
        margin:0px;
    }
    .enviroment_mode {
        font-size: 14px;
    }
    #t2 {
        font-size: 14px;
        float:right;
        padding:0px;
    }
    #t3 {
        padding-left:10px;
    }
    .identity {
        font-weight: bold;
    }
    a.logoutCls   {
        color:navajowhite;
        font-weight: bold;
    }
    #content {
        padding-left: 5px;
        padding-right: 5px;
    }

    
    
    #_menu { 
        display: flex;
        justify-content: center;
        background-color:#dae5f1;
        
        border-bottom: 1px solid #c9d9e9;
    }
    .navigation{
        margin:0;padding:0;list-style:none;border:solid;border-color:#dae5f1;height: 31px;   
    }
    .navigation li{
        float:left;display:block;width:120px;background:#dae5f1;position:relative;z-index:1;margin:0 1px;
    }
    .navigation li a{
        display:block;padding:8px 5px 0 5px;font-weight:700;height:23px;text-decoration:none;color:#fff;text-align:center;color:#333;
    }
    .navigation li a:hover{
        color:#fff;
    }
    .navigation a.selected{
        color:#f00;
    }
    .navigation ul{
        background:#d1d8e;position:absolute;left:0;display:none;margin:0 0 0 -1px;padding:0;list-style:none;
    }
    .navigation ul li{
        width:120px;float:left;border-top:1px solid #fff;}
    .navigation ul a{
        display:block;height:15px;padding:8px 5px;color:#666;
    }
    .navigation ul a:hover{
        text-decoration:underline;
    }
    .navigation ul{
        margin:0 0 0 -2px;
    }
    .disabledMail{
        color:gold ;
        margin: 0px;
        padding:0px;
    }
    #footer {
        position: fixed;
        bottom:0px;
        width:99.5%;
        height:20px;   
            background:#F2F2F2;  
        border-top-width: 1px;
        border-top-color: #ccc;
        border-top-style: solid;  
        margin-top: 1px;
        margin-bottom: 0px;
        margin-left: 3px;
        padding-top: 2px;
        font-size: 10px;
    }
    .spinner {
        position: fixed;
        top: 50%;
        left: 43%;
        margin-left: -50px; /* half width of the spinner gif */
        margin-top: -50px; /* half height of the spinner gif */
        text-align:center;
        z-index:1234;
        overflow: auto;
        width: 350px; /* width of the spinner gif */
        height: 152px; /*hight of the spinner gif +2px to fix IE8 issue */
    }
</style>
 
</head>
    
    <body>
        
        <div id="barra_alta">   
            
            <?php
             $sandbox = null;
             if (Zend_Registry::isRegistered('sandbox')) {
                if(true == Zend_Registry::get('sandbox') ) {
                    $sandbox = "[SANDBOX]";
                }
             }
            
            ?>
            <div id="t0">
                <div id="t1">
                     <h2>
                        <?php  echo $sandbox  ?> 
                        FerieManager 
                        <?php  if(true == Zend_Registry::get('sandbox') ) { ?>
                            <span class='enviroment_mode'>
                       
                            <?php echo ($role == 'Amministratore') ? "[ " . APPLICATION_ENV . " mode ]" : null ?> 
                        </span>      
                        <?php } ?>               
                      </h2>
                </div>
                <div id="t2">
                      <?php echo $top_identity;?> 
                </div>
            </div>
            <div id="t3">
            <?php
            if($role == 'Amministratore') {
              
                $sendmail = Zend_Registry::get('sendmail');
                $sendmailAdmin = Zend_Registry::get('sendmailAdmin');
                if(!$sendmail) {
                    echo '<h4 class=\'disabledMail\'>Invio email disabilitato</h4>';
                }
                if(!$sendmailAdmin) {
                    echo '<h4 class=\'disabledMail\'>Invio email admin disabilitato</h4>';
                }
            }
            ?>
            </div>
        </div>
        
       
<!-- BARRA DI NAVIGAZIONE -->
        <div id="_menu">  <?php echo $menu; ?> </div>      
        
        <br><br> 
        
        
        <div id="content">
            <div id="spinner" class="spinner" style="display:none;">
                <img id="img-spinner" src="<?php echo $this->baseUrl()?>/img/spinner.gif" alt="Loading"/>
            </div>
            <?php echo $this->layout()->content ; ?> 
        </div>
        
        <br>
        
            
        <div id="footer" align="center">
            <?php if(strtolower($role) === 'amministratore') {
                 
                $db = Zend_Registry::get('db');
                $arr = $db->getConfig();
                ?>
                <span>Hostname: <b><?php echo HOSTNAME ?></b> </span>
                <span>Enviroment: <b><?php echo APPLICATION_ENV ?></b> </span>
                <span>DB: <b><?php echo $arr['dbname']; ?></b> </span>
                <span>SERVER: <b><?php echo isset($_SERVER['SERVER_ADDR']) ? $_SERVER['SERVER_ADDR']:   'ND'; ?></b> </span>
                <span>INI_CONFIG:<b><?php echo INI_FILE; ?></b> </span>
            <?php } ?>
        </div>
        
        <br>
        
        
        
    </body>
</html>
