<?php  $this->headLink()->appendStylesheet($this->baseUrl().'/jquery.chromatable-1.3.0/css/style.css'); ?>
<style>
    #noteDeveloper {
        background-color: #EEE;
        padding:5px;
        width: 500px; 
        border-color: #dadada;
        border-style: solid;
        border-width: 1px;
    }
    </style>

<br /> 
<h2>Elenco Ferie assegnate</h2>
<div id="noteDeveloper">
    <p>L'elenco <b>non</b> comprende le richieste inserite e non ancora assegnate. </p>
    <p>L'elenco tiene conto della data di assunzione dell'utente</p>
</div>
<br /> 
<div id="view-content">
    <style>
        #td {
             width: 800px; 
        }
        #colspan {
            text-align: center;
        }
    </style>
    
    
    <table id="td">
        <thead>
            <tr>
                <th>Id utente</th>
                <th>Nome</th>
                <th>Residuo <?php echo date('Y') - 1 ?></th>
                <th colspan='3'id="colspan" > Ferie <?php echo date('Y')  ?>  </th>
                <th colspan='3'id="colspan" >Ferie <?php echo date('Y') + 1?></th>
                 
            </tr>
        </thead>
        <tbody>
            <tr align="center">
                <td colspan="3"></td>
                
                    
                   
                   <td><b> Spettanti </b></td>
                     <td><b> Godute </b></td>
                      <td><b> Rimanenze </b></td>
                  <td><b> Spettanti </b></td>
                     <td><b> Godute </b></td>
                      <td><b> Rimanenze </b></td>
               
                
            </tr>
            
            
            
        <?php
            $i = 0; 
         
            foreach($this->collection as $id => $arrOfYears) {
                ($i%2==1) ? $bgc='#f0f0f0' : $bgc='#FFFFFF';
                $i++;
                $y  = date('Y');
                $y0 = date('Y') - 1 ;
                $y1 = date('Y') + 1 ;
                
                $prev = $arrOfYears['prev'];
                if($prev > 0 ) {
                    $span = "<span style='color:green;'><b>$prev</b></span>";
                } elseif ($prev < 0 ) {
                    $span = "<span style='color:red;'><b>$prev</b></span>";
                } else {
                    $span = "<span style='color:gray;'><b>$prev</b></span>";
                }
                    
                $user = $arrOfYears['user'];
                $assunzione = new Zend_Date($user->getAssunzione());
                
                $const = MAX_FERIE;
                if($assunzione->toString('yyyy') == date('Y')) {
                    $d = $assunzione->toString('d');
                    $m = $assunzione->toString('M');
                    $mesi = (13 - (int)$m);
                    if((int)$d > 16) {
                        $mesi = $mesi - 1 ;
                    }
                    //Prisma_Logger::log($id . ' - ' . $mesi);
                    $const = (2.17 * (int)$mesi);
                }
                
                
                $assegnate = $arrOfYears[$y];
                $spettanti = ($const + $prev);
                $residuo   = ($spettanti - $assegnate);
                
                
                $spettantiNext = (MAX_FERIE + $residuo); 
                $goduteNext    = $arrOfYears[$y1];
                $rimanenzeNext = ($spettantiNext - $goduteNext  );
                if((int)$rimanenzeNext < 0) {
                    $rimanenzeNext = "<span style='color:red;'><b>$rimanenzeNext</b></span>";
                }
                        
                if($residuo > 0) {
                    $spanResiduo = "<span style='color:green;'><b>" . number_format($residuo,2) . "</b></span>";
                } elseif($residuo < 0) {
                    $spanResiduo = "<span style='color:red;'><b>" . number_format($residuo,2) . "</b></span>";
                } else {
                    $spanResiduo = "<span style='color:gray;'><b>" . number_format($residuo,2) . "</b></span>";
                }
                
                
                echo "<tr bgcolor='{$bgc}' align='center'>
                        <td>$id</td>
                        <td>{$this->utente($id, true)}</td>
                        <td>$span</td>
                          
                         
                        <td>" . $spettanti . "</td>
                        <td><b>$assegnate</b></td>
                        <td>" .$spanResiduo . "</td>
                         
                        <td>$spettantiNext</td>
                        <td><b>$arrOfYears[$y1]</b></td>
                        <td>$rimanenzeNext</td>


                         
                    </tr>";
            }
        ?>
        </tbody>  
    </table>
</div>
