<h3>Modifica Password</h3>
 


<form action="" method="POST">
    <table>
        <tbody>
         <!--   <tr><td>Nome</td><td><input type="text" name="nome" value="<?php echo $this->nome ?>" readonly="true" /></td></tr>
            <tr><td>Cognome</td><td><input type="text" name="cognome" value="<?php echo $this->cognome ?>" readonly="true" /></td></tr>
            <tr><td>Username</td><td><input type="text" name="username" value="<?php echo $this->username ?>" readonly="true" /></td></tr>
         -->
            <tr><td>Vecchia password</td><td><input type="password" name="oldpw" /></td></tr>
            <tr><td>Nuova password</td><td><input type="password" name="newpw" /></td></tr>
            <tr><td>Ridigita password</td><td><input type="password" name="renewpw" /></td></tr>
        </tbody>
    </table>
    <input type="hidden" name="user_id" value="<?php echo $this->user_id ?>" />
    <input type="submit" name="submit" value="Salva" />
</form>

