<h3>Modifica Email</h3>

<form action="" method="POST">
    <table>
        <tbody>
         <!--   <tr><td>Nome</td><td><input type="text" name="nome" value="<?php echo $this->nome ?>" size="40px" readonly="true" /></td></tr>
            <tr><td>Cognome</td><td><input type="text" name="cognome" value="<?php echo $this->cognome ?>" size="40px" readonly="true" /></td></tr>
            <tr><td>Username</td><td><input type="text" name="username" value="<?php echo $this->username ?>" size="40px" readonly="true" /></td></tr>
         -->
            <tr><td>Email</td><td><input type="text" name="email" value="<?php echo $this->email ?>" size="40px"  /></td></tr>
        </tbody>
    </table>
    <input type="hidden" name="user_id" value="<?php echo $this->user_id ?>" />
    <input type="submit" name="submit" value="Salva" />
</form>



