<h2>Gestione email</h2>

<p>Consente di gestire gli indirizzi ai quali inviare le richieste di ferie da parte degli operatori</p>


<form method="POST" action="">
    
    <table>
        <tbody>
        <?php ?>
            <tr>
                <td></td>
                <td></td>
            </tr>
        </tbody>
        
        
        
    </table>  
    
    
    
 <input type="submit" name="salva" value="Salva">
 <input type="button" name="add" value="Aggiungi email"
    
    
</form>