<?php
 //$this->headScript()->appendFile($this->baseUrl().'/jquery.chromatable-1.3.0/jquery.chromatable.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/jquery.chromatable-1.3.0/css/style.css');
?>

<script>
  $(function(){  
        $("#sostituzioni").chromatable({
                width: "100%", 
		height: "auto" ,
                scrolling: "yes"
	});	
        
       $("SELECT").selectBox(); 
         $( "input[type=submit]" )
            .button()
            .click(function( event ) {}); 
        
        
        
        
  });
</script>



<h2>Elenco sostituzioni</h2>



<?php if(count($this->elenco) > 0 ) { ?>
<table id="sostituzioni">
    <thead align="left">
    <th>Sostituzione N.</th>
    <th>Citta</th>
    
    <th>Periodo Dal</th>
    <th>Periodo Al</th>
    <th>Status</th>
    <th>Primanota</th>
    </thead>
    <tbody>
<?php foreach($this->elenco as $row) { ?>

    <?php
         $status = 'Da eseguire';
          
         if( $row->getDateStop() >= date('Y-m-d') && $row->getDateStart() <= date('Y-m-d')) {
             $status = 'In corso';
         } elseif($row->getDateStop() < date('Y-m-d')) {
             $status = 'Eseguito';
         }
         
    ?>
    
    
    <tr  >
        <td><?php echo $row->getId() ?></td>
        <td><?php echo $row->getSede() ?></td>
         
        <td><?php echo $this->formatDate($row->getDateStart())  ?></td>
        <td><?php echo $this->formatDate($row->getDateStop()) ?></td>
        <td><?php echo $status ?></td>
        <td>
            <a href="<?php echo $this->baseUrl('index.php')?>/primanota/nuova/sostituzione_id/<?php echo $row->getId() ?>">Aggiungi</a> | 
        <a href="<?php echo $this->baseUrl('index.php')?>/primanota/view/sostituzione_id/<?php echo $row->getId() ?>">Visualizza</a></td>
    </tr>


<?php } ?>
    </tbody>
</table>
  <?php
  if(isset($this->messages )) {
        foreach($this->messages as $message){
            echo $message . "<br/>";
        }
  }
  ?>


 <?php } else { ?>
 
 <h3>Nesuuna sostituzione presente</h3>

<?php } ?>
